import type { Scene } from '@graphlearning/flow'

export const seeingIt: Scene = {
  id: 'aqe-seeing-it',
  padding: 0.16,
  nodes: [
    {
      id: 'code',
      kind: 'code',
      filename: 'aqe.txt',
      minCols: 76,
      label: [
        '# BEFORE the query runs -- explain() shows the static plan:',
        '',
        'AdaptiveSparkPlan isFinalPlan=false          <-- not yet',
        '+- SortMergeJoin [dept_id#7], [id#22], Inner',
        '   +- Sort [dept_id#7 ASC], false, 0',
        '      +- Exchange hashpartitioning(dept_id#7, 200)',
        '',
        '# AFTER it has run -- the SAME DataFrame, explained again:',
        '',
        'AdaptiveSparkPlan isFinalPlan=true           <-- now final',
        '+- == Final Plan ==',
        '   BroadcastHashJoin [dept_id#7], [id#22], Inner  <-- switched',
        '   +- AQEShuffleRead coalesced                    <-- 200 -> 12',
        '+- == Initial Plan ==',
        '   SortMergeJoin [dept_id#7], [id#22], Inner',
        '',
        '# isFinalPlan is the flag to read. False means you are',
        '# looking at a guess; true means you are looking at what',
        '# actually happened, with the initial plan kept beside it.',
        '',
        '# The operators AQE inserts, and what each one tells you:',
        '#   AQEShuffleRead coalesced  -> partitions were merged',
        '#   AQEShuffleRead skewed     -> a partition was split',
        '#   BroadcastHashJoin, where  -> the strategy changed',
        '#     the initial plan had SortMergeJoin',
        '',
        '# The SQL tab shows both plans side by side, which is the',
        '# easiest way to see what it decided and why.',
      ].join('\n'),
    },
  ],
  edges: [],
}
